---

- name: Install EPEL repo.
  yum:
    name: '{{ epel_repo_url }}'
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: '{{ epel_repo_gpg_key_url }}'
    state: present

- name: Install Python PIP
  yum: name=python-pip state=present

- name: Install AWS CLI
  pip: name=awscli state=present

- name: Set home directory of the user
  set_fact:
    home_dir: '/home/{{ aws_cli_user }}'
  when: "not aws_cli_user == 'root'"

- name: Set home directory for root
  set_fact:
    home_dir: /root
  when: "aws_cli_user == 'root'"

- name: 'Create the AWS config directory'
  become: 'yes'
  file: >
   path={{ home_dir }}/.aws
   state=directory
   owner={{ aws_cli_user }}
   group={{ aws_cli_group }}
   mode=0755

- name: 'Copy AWS CLI config'
  become: 'yes'
  template: >
   src=aws-cli-config.j2
   dest={{ home_dir }}/.aws/config
   owner={{ aws_cli_user }}
   group={{ aws_cli_group }}
   mode=0600

- name: 'Copy AWS CLI credentials'
  tags: 'aws-cli'
  become: 'yes'
  template: >
   src=aws-cli-credentials.j2
   dest={{ home_dir }}/.aws/credentials
   owner={{ aws_cli_user }}
   group={{ aws_cli_group }}
   mode=0600
